In [1]:
import numpy as np
import pandas as pd

In [2]:
parks = pd.read_csv("parks.csv")

In [3]:
parks

,year,rank,city,med_park_size_data,med_park_size_points,park_pct_city_data,park_pct_city_points,pct_near_park_data,pct_near_park_points,spend_per_resident_data,...,rec_sr_points,restroom_data,restroom_points,splashground_data,splashground_points,amenities_points,total_points,total_pct,city_dup,park_benches
0,2020,1,Minneapolis,5.7,26.0,15%,38.0,98%,98.0,$319,...,100.0,2.9,91.0,4.0,100.0,79.3,341.0,85.3,Minneapolis,NaN
1,2020,2,"Washington, D.C.",1.4,5.0,24%,50.0,98%,98.0,$307,...,100.0,2.6,80.0,4.1,100.0,80.3,333.0,83.3,"Washington, D.C.",NaN
2,2020,3,St. Paul,3.2,14.0,15%,39.0,99%,99.0,$219,...,100.0,3.2,100.0,1.3,47.0,78.0,330.0,82.5,St. Paul,NaN
3,2020,4,"Arlington, Virginia",2.4,10.0,11%,28.0,99%,99.0,$301,...,76.0,3.1,97.0,2.2,81.0,89.0,326.0,81.5,"Arlington, Virginia",NaN
4,2020,5,Cincinnati,4.4,20.0,14%,36.0,82%,74.0,$190,...,100.0,3.2,98.0,4.5,100.0,92.5,323.0,80.6,Cincinnati,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708,2012,36,Indianapolis,10.3,20.0,4.8%,4.0,32%,6.0,$43.61,...,NaN,NaN,NaN,NaN,NaN,NaN,37.0,31.0,NaN,1.5
709,2012,36,Mesa,3.2,7.0,2.6%,1.0,60%,22.0,$60.96,...,NaN,NaN,NaN,NaN,NaN,NaN,37.0,31.0,NaN,1.5
710,2012,38,Louisville,7.3,15.0,6.7%,6.0,32%,6.0,$50.76,...,NaN,NaN,NaN,NaN,NaN,NaN,35.0,29.0,NaN,1.0
711,2012,39,Charlotte,19.9,20.0,4.1%,3.0,26%,2.0,$78.94,...,NaN,NaN,NaN,NaN,NaN,NaN,34.0,28.5,NaN,1.0
712,2012,40,Fresno,4.9,10.0,2.1%,1.0,35%,8.0,$54.98,...,NaN,NaN,NaN,NaN,NaN,NaN,26.0,21.5,NaN,0.5

## First Try

In [4]:
lookup = pd.read_csv("city_state_lookup.csv")

In [5]:
lookup

            city       state  pop2020  pop2010  area2020
0       New York    New York  8804190  8175133     300.5
1    Los Angeles  California  3898747  3792621     469.5
2        Chicago    Illinois  2746388  2695598     227.7
3        Houston       Texas  2304580  2100263     640.4
4        Phoenix     Arizona  1608139  1445632     518.0
..           ...         ...      ...      ...       ...
321  Federal Way  Washington   101030    89306      22.3
322      Clinton    Michigan   100513    96796      28.1
323     Edinburg       Texas   100243    77100      44.7
324        Nampa       Idaho   100200    81557      33.5
325      Roanoke    Virginia   100011    97032      42.5

[326 rows x 5 columns]

In [6]:
parks["city"] = parks.city.str.split(",").str.get(0)

In [7]:
merged = pd.merge(parks, lookup, how = "left", on = "city")

In [9]:
merged

,year,rank,city,med_park_size_data,med_park_size_points,park_pct_city_data,park_pct_city_points,pct_near_park_data,pct_near_park_points,spend_per_resident_data,...,splashground_points,amenities_points,total_points,total_pct,city_dup,park_benches,state,pop2020,pop2010,area2020
0,2020,1,Minneapolis,5.7,26.0,15%,38.0,98%,98.0,$319,...,100.0,79.3,341.0,85.3,Minneapolis,NaN,Minnesota,429954.0,382578.0,54.0
1,2020,2,Washington,1.4,5.0,24%,50.0,98%,98.0,$307,...,100.0,80.3,333.0,83.3,"Washington, D.C.",NaN,District of Columbia,689545.0,601723.0,61.1
2,2020,3,St. Paul,3.2,14.0,15%,39.0,99%,99.0,$219,...,47.0,78.0,330.0,82.5,St. Paul,NaN,NaN,NaN,NaN,NaN
3,2020,4,Arlington,2.4,10.0,11%,28.0,99%,99.0,$301,...,81.0,89.0,326.0,81.5,"Arlington, Virginia",NaN,Texas,394266.0,365438.0,95.9
4,2020,5,Cincinnati,4.4,20.0,14%,36.0,82%,74.0,$190,...,100.0,92.5,323.0,80.6,Cincinnati,NaN,Ohio,309317.0,296943.0,77.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,2012,36,Indianapolis,10.3,20.0,4.8%,4.0,32%,6.0,$43.61,...,NaN,NaN,37.0,31.0,NaN,1.5,Indiana,887642.0,820445.0,361.6
742,2012,36,Mesa,3.2,7.0,2.6%,1.0,60%,22.0,$60.96,...,NaN,NaN,37.0,31.0,NaN,1.5,Arizona,504258.0,439041.0,138.7
743,2012,38,Louisville,7.3,15.0,6.7%,6.0,32%,6.0,$50.76,...,NaN,NaN,35.0,29.0,NaN,1.0,Kentucky,633045.0,597337.0,263.5
744,2012,39,Charlotte,19.9,20.0,4.1%,3.0,26%,2.0,$78.94,...,NaN,NaN,34.0,28.5,NaN,1.0,North Carolina,874579.0,731424.0,308.3
745,2012,40,Fresno,4.9,10.0,2.1%,1.0,35%,8.0,$54.98,...,NaN,NaN,26.0,21.5,NaN,0.5,California,542107.0,494665.0,115.2

In [10]:
isna = merged.state.isna()

In [11]:
merged[isna]

,year,rank,city,med_park_size_data,med_park_size_points,park_pct_city_data,park_pct_city_points,pct_near_park_data,pct_near_park_points,spend_per_resident_data,...,splashground_points,amenities_points,total_points,total_pct,city_dup,park_benches,state,pop2020,pop2010,area2020
2,2020,3,St. Paul,3.2,14.0,15%,39.0,99%,99.0,$219,...,47.0,78.0,330.0,82.5,St. Paul,NaN,NaN,NaN,NaN,NaN
85,2020,82,Winston-Salem,9.2,43.0,5%,11.0,37%,4.0,$81,...,100.0,54.7,154.0,38.4,Winston-Salem,NaN,NaN,NaN,NaN,NaN
98,2020,95,Charlotte/Mecklenburg County,16.5,50.0,6%,13.0,37%,3.0,$56,...,28.0,27.3,119.0,29.8,Charlotte,NaN,NaN,NaN,NaN,NaN
102,2019,2,St. Paul,3.2,15.0,15%,40.0,98%,97.5,$220,...,50.0,80.4,NaN,83.2,St. Paul,NaN,NaN,NaN,NaN,NaN
190,2019,86,Winston-Salem,9.2,45.0,5%,10.0,36%,7.5,$62,...,100.0,52.5,NaN,35.0,Winston-Salem,NaN,NaN,NaN,NaN,NaN
200,2019,95,Charlotte/Mecklenburg County,16.5,50.0,6%,12.5,36%,7.5,$48,...,25.0,27.9,NaN,28.9,Charlotte,NaN,NaN,NaN,NaN,NaN
203,2018,2,St. Paul,3.2,6.0,15%,16.0,96%,38.0,$218,...,15.0,32.0,132.0,82.4,St. Paul,NaN,NaN,NaN,NaN,NaN
298,2018,92,Winston-Salem,9.2,18.0,5%,4.0,35%,4.0,$48,...,34.0,18.0,51.0,31.9,Winston-Salem,NaN,NaN,NaN,NaN,NaN
305,2017,2,St. Paul,3.7,7.0,15%,16.0,96%,39.0,$202,...,NaN,17.0,82.5,NaN,St. Paul,5.0,NaN,NaN,NaN,NaN
402,2017,93,Winston-Salem,9.8,19.0,4%,4.0,35%,5.0,$42,...,NaN,8.0,32.5,NaN,Winston-Salem,1.5,NaN,NaN,NaN,NaN
409,2016,2,St. Paul,3.7,7.0,15%,16.0,96%,39.0,$212,...,NaN,17.0,99.0,82.5,St. Paul,5.0,NaN,NaN,NaN,NaN
506,2016,93,Winston-Salem,9.8,19.0,4%,4.0,35%,5.0,$44,...,NaN,8.0,40.0,33.5,Winston-Salem,1.5,NaN,NaN,NaN,NaN
512,2015,1,St. Paul,3.7,7.0,15.3%,16.0,96%,40.0,$210,...,NaN,71.0,18.0,84.0,NaN,5.0,NaN,NaN,NaN,NaN

## Second, Correct Try

In [12]:
parks = pd.read_csv("parks.csv")
lookup = pd.read_csv("city_state_lookup.csv")

In [13]:
lookup.loc[lookup.city == "Arlington", "city"] = "Arlington, Texas"

lookup.loc[lookup.city == "Washington", "city"] = "Washington, D.C."
parks.loc[parks.city == "Washington, DC", "city"] = "Washington, D.C."

lookup.loc[lookup.city == "Saint Paul", "city"] = "St. Paul"

lookup.loc[lookup.city == "Winston–Salem", "city"] = "Winston-Salem"

Add St. Paul, Winston-Salem, and Charlotte:

In [14]:
merged = pd.merge(parks, lookup, how = "left", on = "city")

In [15]:
merged

,year,rank,city,med_park_size_data,med_park_size_points,park_pct_city_data,park_pct_city_points,pct_near_park_data,pct_near_park_points,spend_per_resident_data,...,splashground_points,amenities_points,total_points,total_pct,city_dup,park_benches,state,pop2020,pop2010,area2020
0,2020,1,Minneapolis,5.7,26.0,15%,38.0,98%,98.0,$319,...,100.0,79.3,341.0,85.3,Minneapolis,NaN,Minnesota,429954.0,382578.0,54.0
1,2020,2,"Washington, D.C.",1.4,5.0,24%,50.0,98%,98.0,$307,...,100.0,80.3,333.0,83.3,"Washington, D.C.",NaN,District of Columbia,689545.0,601723.0,61.1
2,2020,3,St. Paul,3.2,14.0,15%,39.0,99%,99.0,$219,...,47.0,78.0,330.0,82.5,St. Paul,NaN,Minnesota,311527.0,285068.0,52.0
3,2020,4,"Arlington, Virginia",2.4,10.0,11%,28.0,99%,99.0,$301,...,81.0,89.0,326.0,81.5,"Arlington, Virginia",NaN,NaN,NaN,NaN,NaN
4,2020,5,Cincinnati,4.4,20.0,14%,36.0,82%,74.0,$190,...,100.0,92.5,323.0,80.6,Cincinnati,NaN,Ohio,309317.0,296943.0,77.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,2012,36,Indianapolis,10.3,20.0,4.8%,4.0,32%,6.0,$43.61,...,NaN,NaN,37.0,31.0,NaN,1.5,Indiana,887642.0,820445.0,361.6
742,2012,36,Mesa,3.2,7.0,2.6%,1.0,60%,22.0,$60.96,...,NaN,NaN,37.0,31.0,NaN,1.5,Arizona,504258.0,439041.0,138.7
743,2012,38,Louisville,7.3,15.0,6.7%,6.0,32%,6.0,$50.76,...,NaN,NaN,35.0,29.0,NaN,1.0,Kentucky,633045.0,597337.0,263.5
744,2012,39,Charlotte,19.9,20.0,4.1%,3.0,26%,2.0,$78.94,...,NaN,NaN,34.0,28.5,NaN,1.0,North Carolina,874579.0,731424.0,308.3
745,2012,40,Fresno,4.9,10.0,2.1%,1.0,35%,8.0,$54.98,...,NaN,NaN,26.0,21.5,NaN,0.5,California,542107.0,494665.0,115.2

In [25]:
merged.loc[merged.state.isna()]

Empty DataFrame
Columns: [year, rank, city, med_park_size_data, med_park_size_points, park_pct_city_data, park_pct_city_points, pct_near_park_data, pct_near_park_points, spend_per_resident_data, spend_per_resident_points, basketball_data, basketball_points, dogpark_data, dogpark_points, playground_data, playground_points, rec_sr_data, rec_sr_points, restroom_data, restroom_points, splashground_data, splashground_points, amenities_points, total_points, total_pct, park_benches, state, pop2020, pop2010, area2020]
Index: []

[0 rows x 31 columns]

In [17]:
merged = merged.drop("city_dup", axis = 1)

In [18]:
city_state = merged.city.str.split(",")

In [19]:
merged["city"] = city_state.str.get(0)

In [20]:
state = city_state.str.get(1).str.strip()

In [21]:
to_change = ~state.isna() & (state != "D.C.")

In [22]:
merged.loc[to_change, "state"] = state[to_change]

In [23]:
merged

,year,rank,city,med_park_size_data,med_park_size_points,park_pct_city_data,park_pct_city_points,pct_near_park_data,pct_near_park_points,spend_per_resident_data,...,splashground_data,splashground_points,amenities_points,total_points,total_pct,park_benches,state,pop2020,pop2010,area2020
0,2020,1,Minneapolis,5.7,26.0,15%,38.0,98%,98.0,$319,...,4.0,100.0,79.3,341.0,85.3,NaN,Minnesota,429954.0,382578.0,54.0
1,2020,2,Washington,1.4,5.0,24%,50.0,98%,98.0,$307,...,4.1,100.0,80.3,333.0,83.3,NaN,District of Columbia,689545.0,601723.0,61.1
2,2020,3,St. Paul,3.2,14.0,15%,39.0,99%,99.0,$219,...,1.3,47.0,78.0,330.0,82.5,NaN,Minnesota,311527.0,285068.0,52.0
3,2020,4,Arlington,2.4,10.0,11%,28.0,99%,99.0,$301,...,2.2,81.0,89.0,326.0,81.5,NaN,Virginia,NaN,NaN,NaN
4,2020,5,Cincinnati,4.4,20.0,14%,36.0,82%,74.0,$190,...,4.5,100.0,92.5,323.0,80.6,NaN,Ohio,309317.0,296943.0,77.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,2012,36,Indianapolis,10.3,20.0,4.8%,4.0,32%,6.0,$43.61,...,NaN,NaN,NaN,37.0,31.0,1.5,Indiana,887642.0,820445.0,361.6
742,2012,36,Mesa,3.2,7.0,2.6%,1.0,60%,22.0,$60.96,...,NaN,NaN,NaN,37.0,31.0,1.5,Arizona,504258.0,439041.0,138.7
743,2012,38,Louisville,7.3,15.0,6.7%,6.0,32%,6.0,$50.76,...,NaN,NaN,NaN,35.0,29.0,1.0,Kentucky,633045.0,597337.0,263.5
744,2012,39,Charlotte,19.9,20.0,4.1%,3.0,26%,2.0,$78.94,...,NaN,NaN,NaN,34.0,28.5,1.0,North Carolina,874579.0,731424.0,308.3
745,2012,40,Fresno,4.9,10.0,2.1%,1.0,35%,8.0,$54.98,...,NaN,NaN,NaN,26.0,21.5,0.5,California,542107.0,494665.0,115.2

In [24]:
merged.loc[merged.city == "Charlotte/Mecklenburg County", "state"] = "North Carolina"

In [26]:
merged.to_csv("parks_final.csv", index = False)